//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StackOverFlowQuestionData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class StackOverFlowQuestionData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumeService.ServiceReference1.StackOverFlowQuestionItemData[] itemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ConsumeService.ServiceReference1.StackOverFlowQuestionItemData[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StackOverFlowQuestionItemData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class StackOverFlowQuestionItemData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumeService.ServiceReference1.ArrayOfString tagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumeService.ServiceReference1.StackOverFlowOwnerInfo ownerField;
        
        private int AnswerCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ConsumeService.ServiceReference1.ArrayOfString tags {
            get {
                return this.tagsField;
            }
            set {
                if ((object.ReferenceEquals(this.tagsField, value) != true)) {
                    this.tagsField = value;
                    this.RaisePropertyChanged("tags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ConsumeService.ServiceReference1.StackOverFlowOwnerInfo owner {
            get {
                return this.ownerField;
            }
            set {
                if ((object.ReferenceEquals(this.ownerField, value) != true)) {
                    this.ownerField = value;
                    this.RaisePropertyChanged("owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int AnswerCount {
            get {
                return this.AnswerCountField;
            }
            set {
                if ((this.AnswerCountField.Equals(value) != true)) {
                    this.AnswerCountField = value;
                    this.RaisePropertyChanged("AnswerCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string QuestionID {
            get {
                return this.QuestionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionIDField, value) != true)) {
                    this.QuestionIDField = value;
                    this.RaisePropertyChanged("QuestionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StackOverFlowOwnerInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class StackOverFlowOwnerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string account_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string profile_imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string linkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string account_id {
            get {
                return this.account_idField;
            }
            set {
                if ((object.ReferenceEquals(this.account_idField, value) != true)) {
                    this.account_idField = value;
                    this.RaisePropertyChanged("account_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((object.ReferenceEquals(this.user_idField, value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string user_type {
            get {
                return this.user_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.user_typeField, value) != true)) {
                    this.user_typeField = value;
                    this.RaisePropertyChanged("user_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string profile_image {
            get {
                return this.profile_imageField;
            }
            set {
                if ((object.ReferenceEquals(this.profile_imageField, value) != true)) {
                    this.profile_imageField = value;
                    this.RaisePropertyChanged("profile_image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string link {
            get {
                return this.linkField;
            }
            set {
                if ((object.ReferenceEquals(this.linkField, value) != true)) {
                    this.linkField = value;
                    this.RaisePropertyChanged("link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StackOverFlowAnswerData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class StackOverFlowAnswerData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumeService.ServiceReference1.StackOverFlowAnswerItemData[] itemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ConsumeService.ServiceReference1.StackOverFlowAnswerItemData[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StackOverFlowAnswerItemData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class StackOverFlowAnswerItemData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumeService.ServiceReference1.ArrayOfString tagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumeService.ServiceReference1.StackOverFlowOwnerInfo ownerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ConsumeService.ServiceReference1.ArrayOfString tags {
            get {
                return this.tagsField;
            }
            set {
                if ((object.ReferenceEquals(this.tagsField, value) != true)) {
                    this.tagsField = value;
                    this.RaisePropertyChanged("tags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ConsumeService.ServiceReference1.StackOverFlowOwnerInfo owner {
            get {
                return this.ownerField;
            }
            set {
                if ((object.ReferenceEquals(this.ownerField, value) != true)) {
                    this.ownerField = value;
                    this.RaisePropertyChanged("owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string QuestionID {
            get {
                return this.QuestionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionIDField, value) != true)) {
                    this.QuestionIDField = value;
                    this.RaisePropertyChanged("QuestionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AnswerID {
            get {
                return this.AnswerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerIDField, value) != true)) {
                    this.AnswerIDField = value;
                    this.RaisePropertyChanged("AnswerID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.StackOverFlowApiSoap")]
    public interface StackOverFlowApiSoap {
        
        // CODEGEN: Generating message contract since element name GetQuestionsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuestions", ReplyAction="*")]
        ConsumeService.ServiceReference1.GetQuestionsResponse GetQuestions(ConsumeService.ServiceReference1.GetQuestionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuestions", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeService.ServiceReference1.GetQuestionsResponse> GetQuestionsAsync(ConsumeService.ServiceReference1.GetQuestionsRequest request);
        
        // CODEGEN: Generating message contract since element name question_id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAnswers", ReplyAction="*")]
        ConsumeService.ServiceReference1.GetAnswersResponse GetAnswers(ConsumeService.ServiceReference1.GetAnswersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAnswers", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeService.ServiceReference1.GetAnswersResponse> GetAnswersAsync(ConsumeService.ServiceReference1.GetAnswersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuestionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuestions", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeService.ServiceReference1.GetQuestionsRequestBody Body;
        
        public GetQuestionsRequest() {
        }
        
        public GetQuestionsRequest(ConsumeService.ServiceReference1.GetQuestionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetQuestionsRequestBody {
        
        public GetQuestionsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuestionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuestionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeService.ServiceReference1.GetQuestionsResponseBody Body;
        
        public GetQuestionsResponse() {
        }
        
        public GetQuestionsResponse(ConsumeService.ServiceReference1.GetQuestionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQuestionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumeService.ServiceReference1.StackOverFlowQuestionData GetQuestionsResult;
        
        public GetQuestionsResponseBody() {
        }
        
        public GetQuestionsResponseBody(ConsumeService.ServiceReference1.StackOverFlowQuestionData GetQuestionsResult) {
            this.GetQuestionsResult = GetQuestionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAnswersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAnswers", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeService.ServiceReference1.GetAnswersRequestBody Body;
        
        public GetAnswersRequest() {
        }
        
        public GetAnswersRequest(ConsumeService.ServiceReference1.GetAnswersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAnswersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string question_id;
        
        public GetAnswersRequestBody() {
        }
        
        public GetAnswersRequestBody(string question_id) {
            this.question_id = question_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAnswersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAnswersResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeService.ServiceReference1.GetAnswersResponseBody Body;
        
        public GetAnswersResponse() {
        }
        
        public GetAnswersResponse(ConsumeService.ServiceReference1.GetAnswersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAnswersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumeService.ServiceReference1.StackOverFlowAnswerData GetAnswersResult;
        
        public GetAnswersResponseBody() {
        }
        
        public GetAnswersResponseBody(ConsumeService.ServiceReference1.StackOverFlowAnswerData GetAnswersResult) {
            this.GetAnswersResult = GetAnswersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StackOverFlowApiSoapChannel : ConsumeService.ServiceReference1.StackOverFlowApiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StackOverFlowApiSoapClient : System.ServiceModel.ClientBase<ConsumeService.ServiceReference1.StackOverFlowApiSoap>, ConsumeService.ServiceReference1.StackOverFlowApiSoap {
        
        public StackOverFlowApiSoapClient() {
        }
        
        public StackOverFlowApiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StackOverFlowApiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StackOverFlowApiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StackOverFlowApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeService.ServiceReference1.GetQuestionsResponse ConsumeService.ServiceReference1.StackOverFlowApiSoap.GetQuestions(ConsumeService.ServiceReference1.GetQuestionsRequest request) {
            return base.Channel.GetQuestions(request);
        }
        
        public ConsumeService.ServiceReference1.StackOverFlowQuestionData GetQuestions() {
            ConsumeService.ServiceReference1.GetQuestionsRequest inValue = new ConsumeService.ServiceReference1.GetQuestionsRequest();
            inValue.Body = new ConsumeService.ServiceReference1.GetQuestionsRequestBody();
            ConsumeService.ServiceReference1.GetQuestionsResponse retVal = ((ConsumeService.ServiceReference1.StackOverFlowApiSoap)(this)).GetQuestions(inValue);
            return retVal.Body.GetQuestionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeService.ServiceReference1.GetQuestionsResponse> ConsumeService.ServiceReference1.StackOverFlowApiSoap.GetQuestionsAsync(ConsumeService.ServiceReference1.GetQuestionsRequest request) {
            return base.Channel.GetQuestionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeService.ServiceReference1.GetQuestionsResponse> GetQuestionsAsync() {
            ConsumeService.ServiceReference1.GetQuestionsRequest inValue = new ConsumeService.ServiceReference1.GetQuestionsRequest();
            inValue.Body = new ConsumeService.ServiceReference1.GetQuestionsRequestBody();
            return ((ConsumeService.ServiceReference1.StackOverFlowApiSoap)(this)).GetQuestionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeService.ServiceReference1.GetAnswersResponse ConsumeService.ServiceReference1.StackOverFlowApiSoap.GetAnswers(ConsumeService.ServiceReference1.GetAnswersRequest request) {
            return base.Channel.GetAnswers(request);
        }
        
        public ConsumeService.ServiceReference1.StackOverFlowAnswerData GetAnswers(string question_id) {
            ConsumeService.ServiceReference1.GetAnswersRequest inValue = new ConsumeService.ServiceReference1.GetAnswersRequest();
            inValue.Body = new ConsumeService.ServiceReference1.GetAnswersRequestBody();
            inValue.Body.question_id = question_id;
            ConsumeService.ServiceReference1.GetAnswersResponse retVal = ((ConsumeService.ServiceReference1.StackOverFlowApiSoap)(this)).GetAnswers(inValue);
            return retVal.Body.GetAnswersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeService.ServiceReference1.GetAnswersResponse> ConsumeService.ServiceReference1.StackOverFlowApiSoap.GetAnswersAsync(ConsumeService.ServiceReference1.GetAnswersRequest request) {
            return base.Channel.GetAnswersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeService.ServiceReference1.GetAnswersResponse> GetAnswersAsync(string question_id) {
            ConsumeService.ServiceReference1.GetAnswersRequest inValue = new ConsumeService.ServiceReference1.GetAnswersRequest();
            inValue.Body = new ConsumeService.ServiceReference1.GetAnswersRequestBody();
            inValue.Body.question_id = question_id;
            return ((ConsumeService.ServiceReference1.StackOverFlowApiSoap)(this)).GetAnswersAsync(inValue);
        }
    }
}
