//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LIB_LIAQUATEntities : DbContext
    {
        public LIB_LIAQUATEntities()
            : base("name=LIB_LIAQUATEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_AUTHOR> TBL_AUTHOR { get; set; }
        public virtual DbSet<TBL_BOOK> TBL_BOOK { get; set; }
        public virtual DbSet<TBL_CATEGORY> TBL_CATEGORY { get; set; }
    
        public virtual ObjectResult<usp_GET_BOOK_LIST_Result> usp_GET_BOOK_LIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GET_BOOK_LIST_Result>("usp_GET_BOOK_LIST");
        }
    
        public virtual ObjectResult<usp_GET_CATEGORIES_Result> usp_GET_CATEGORIES(Nullable<int> cATEGORY_ID, Nullable<int> pARENT_CATEGORY_ID)
        {
            var cATEGORY_IDParameter = cATEGORY_ID.HasValue ?
                new ObjectParameter("CATEGORY_ID", cATEGORY_ID) :
                new ObjectParameter("CATEGORY_ID", typeof(int));
    
            var pARENT_CATEGORY_IDParameter = pARENT_CATEGORY_ID.HasValue ?
                new ObjectParameter("PARENT_CATEGORY_ID", pARENT_CATEGORY_ID) :
                new ObjectParameter("PARENT_CATEGORY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GET_CATEGORIES_Result>("usp_GET_CATEGORIES", cATEGORY_IDParameter, pARENT_CATEGORY_IDParameter);
        }
    }
}
