//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CATEGORY
    {
        public int CATEGORY_ID { get; set; }
        public Nullable<int> PARENT_CATEGORY_ID { get; set; }
        public string CATEGORY_NAME { get; set; }
    }
}
