
CREATE DATABASE LIB_LIAQUAT
GO
USE LIB_LIAQUAT
GO
CREATE TABLE DBO.TBL_CATEGORY(
 CATEGORY_ID INT IDENTITY(1,1)
,PARENT_CATEGORY_ID INT
,CATEGORY_NAME NVARCHAR(150)
)
GO
--truncate table TBL_CATEGORY

INSERT INTO DBO.TBL_CATEGORY VALUES
 (NULL,'Computer Books')
,(NULL,'Science Books')
,(NULL,'History Books')
,(NULL,'Fiction Stories')
GO
INSERT INTO DBO.TBL_CATEGORY VALUES
 (1,'Programming'),(1,'Database'),(1,'Aplication')
,(2,'Biology'),(2,'Chemistyr'),(2,'Physics')
,(3,'Social')
,(4,'Comics')
go

--select * from TBL_CATEGORY

CREATE TABLE DBO.TBL_AUTHOR(
 AUTHOR_ID INT IDENTITY(1,1)
,AUTHOR_NAME NVARCHAR(150)
)
GO
INSERT INTO DBO.TBL_AUTHOR(AUTHOR_NAME) VALUES('Jon'),('Liaquat'),('Mike')
GO
--DROP TABLE TBL_BOOK
CREATE TABLE DBO.TBL_BOOK(
 BOOK_ID INT IDENTITY(1,1)
,AUTHOR_ID INT
,CATEGORY_ID INT
,BOOK_TITLE NVARCHAR(150)
,BOOK_EDITION NVARCHAR(150)
,BOOK_IBAN_NO NVARCHAR(150)
)
GO
INSERT INTO DBO.TBL_BOOK VALUES
 (1,5,'C# Complete','Third Edition','12345467890')
,(2,5,'MVC.Net Complete','Third Edition','12345467891')
,(1,5,'VB.Net Complete','Third Edition','12345467892')
,(2,7,'Microsoft Office Complete','Third Edition','12345467893')
,(2,6,'MS-SQL SERVER','Third Edition','12345467894')
,(2,6,'MY SQL','Third Edition','12345467895')
,(2,6,'SQLite','Third Edition','12345467896')
GO

ALTER PROCEDURE DBO.usp_GET_CATEGORIES
  @CATEGORY_ID INT
,@PARENT_CATEGORY_ID INT
AS


SET @CATEGORY_ID=ISNULL(@CATEGORY_ID,0)
SET @PARENT_CATEGORY_ID=ISNULL(@PARENT_CATEGORY_ID,0)

SELECT * FROM TBL_CATEGORY WHERE 1=1
AND (@CATEGORY_ID=0 OR CATEGORY_ID=@CATEGORY_ID)
AND ISNULL(PARENT_CATEGORY_ID,0)=@PARENT_CATEGORY_ID
GO

CREATE PROCEDURE DBO.usp_GET_BOOK_LIST
AS

SELECT 
 C.CATEGORY_ID
,C.CATEGORY_NAME
,A.AUTHOR_NAME
,B.BOOK_TITLE
,B.BOOK_EDITION
,B.BOOK_IBAN_NO

FROM DBO.TBL_BOOK B
INNER JOIN DBO.TBL_AUTHOR A ON B.AUTHOR_ID=A.AUTHOR_ID
INNER JOIN DBO.TBL_CATEGORY C ON B.CATEGORY_ID=C.CATEGORY_ID
